#!/usr/bin/env bash
# muselab — one-shot macOS installer (user-level LaunchAgent)
# Usage: bash scripts/install-macos.sh
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
ok()   { printf "  \033[32m✓\033[0m %s\n" "$*"; }
warn() { printf "  \033[33m!\033[0m %s\n" "$*"; }
err()  { printf "  \033[31m✗\033[0m %s\n" "$*" >&2; }
ask()  { local q="$1" def="${2:-}" ans; read -rp "  $q ${def:+[$def]} " ans; echo "${ans:-$def}"; }

bold "muselab — macOS installer"
echo  "  Repo: $REPO"
echo

# ----- 1. Prerequisites ---------------------------------------------------
bold "1/5  Checking prerequisites"
if [[ "$(uname -s)" != "Darwin" ]]; then
  err "This script is for macOS only. On Linux use install-linux.sh"
  exit 1
fi

if ! command -v uv >/dev/null 2>&1; then
  err "uv not found. Install it first:"
  echo "      curl -LsSf https://astral.sh/uv/install.sh | sh"
  echo "      # or:  brew install uv"
  exit 1
fi
UV="$(command -v uv)"
ok "uv: $UV"

if ! command -v claude >/dev/null 2>&1; then
  warn "claude CLI not found. Anthropic models won't work until you install it"
  warn "  and run 'claude login'. Non-Claude providers will still work via API keys."
else
  ok "claude CLI: $(command -v claude)"
  if [[ ! -d "$HOME/.claude" ]]; then
    warn "  ~/.claude not found — run 'claude login' before installing for OAuth to work"
  fi
fi

# ----- 2. Python deps ----------------------------------------------------
bold "2/5  Installing Python dependencies (uv sync)"
uv sync --quiet
ok "deps installed"

# ----- 3. .env -----------------------------------------------------------
bold "3/5  Configuring .env"
if [[ -f .env ]]; then
  ok ".env already exists — keeping it as is"
else
  TOKEN="$(openssl rand -hex 32)"

  echo
  echo "  Archive dir = where Muse can read/write (NEVER point at \$HOME or /)"
  ARCHIVE="$(ask 'Archive dir (absolute path):' "$HOME/muselab-archive")"
  ARCHIVE="${ARCHIVE/#\~/$HOME}"
  mkdir -p "$ARCHIVE"

  cat > .env <<EOF
# Generated by install-macos.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
MUSELAB_TOKEN=$TOKEN
MUSELAB_ROOT=$ARCHIVE
MUSELAB_HOST=127.0.0.1
MUSELAB_PORT=8765
MUSELAB_MODEL=claude-sonnet-4-6
EOF
  chmod 600 .env
  ok ".env created (mode 600)"
  ok "  MUSELAB_ROOT = $ARCHIVE"
  ok "  MUSELAB_TOKEN = ${TOKEN:0:6}…${TOKEN: -4}  (full token saved in .env)"
fi

# ----- 4. LaunchAgent ----------------------------------------------------
bold "4/5  Installing LaunchAgent"
AGENT_DIR="$HOME/Library/LaunchAgents"
LOG_DIR="$HOME/Library/Logs/muselab"
mkdir -p "$AGENT_DIR" "$LOG_DIR"

PLIST="$AGENT_DIR/com.muselab.plist"

# Build PATH that the agent will inherit — must include uv's dir and brew dirs so
# subprocesses (claude CLI, node for MCP) can be found by absolute resolution.
UV_DIR="$(dirname "$UV")"
PATH_DIRS="$UV_DIR:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

sed -e "s|{{REPO_PATH}}|$REPO|g" \
    -e "s|{{UV_PATH}}|$UV|g" \
    -e "s|{{PATH_DIRS}}|$PATH_DIRS|g" \
    -e "s|{{HOME_DIR}}|$HOME|g" \
    scripts/templates/com.muselab.plist.tmpl > "$PLIST"
ok "plist: $PLIST"

# Reload — unload first in case an old version is loaded
launchctl unload "$PLIST" 2>/dev/null || true
launchctl load -w "$PLIST"
sleep 1
if launchctl list | grep -q com.muselab; then
  ok "agent loaded"
else
  err "agent failed to load — check $LOG_DIR/stderr.log"
  exit 1
fi

# ----- 5. Sanity check ---------------------------------------------------
bold "5/5  Sanity check"
sleep 2
if curl -fs -o /dev/null -m 5 http://127.0.0.1:8765/ 2>/dev/null; then
  ok "muselab responding at http://localhost:8765"
else
  warn "couldn't reach http://localhost:8765 yet — give it a few more seconds"
  warn "  tail logs: tail -f $LOG_DIR/stderr.log"
fi

echo
bold "✓ muselab installed"
echo  "  Open  → http://localhost:8765"
echo  "  Token → grep MUSELAB_TOKEN .env"
echo
echo  "  Useful commands:"
echo  "    launchctl list | grep muselab          # check loaded"
echo  "    launchctl kickstart -k gui/\$UID/com.muselab    # restart"
echo  "    tail -f $LOG_DIR/stderr.log            # tail logs"
echo  "    bash scripts/uninstall-macos.sh        # remove autostart"
