#!/usr/bin/env bash
# muselab — one-shot Linux installer (user-level systemd service)
# Usage: bash scripts/install-linux.sh
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
ok()   { printf "  \033[32m✓\033[0m %s\n" "$*"; }
warn() { printf "  \033[33m!\033[0m %s\n" "$*"; }
err()  { printf "  \033[31m✗\033[0m %s\n" "$*" >&2; }
ask()  { local q="$1" def="${2:-}" ans; read -rp "  $q ${def:+[$def]} " ans; echo "${ans:-$def}"; }

bold "muselab — Linux installer"
echo  "  Repo: $REPO"
echo

# ----- 1. Prerequisites ---------------------------------------------------
bold "1/5  Checking prerequisites"
if ! command -v uv >/dev/null 2>&1; then
  err "uv not found. Install it first:"
  echo "      curl -LsSf https://astral.sh/uv/install.sh | sh"
  exit 1
fi
UV="$(command -v uv)"
ok "uv: $UV"

if ! command -v claude >/dev/null 2>&1; then
  warn "claude CLI not found. Anthropic models won't work until you install it"
  warn "  and run 'claude login'. Non-Claude providers will still work via API keys."
else
  ok "claude CLI: $(command -v claude)"
fi

# MCP runtimes — non-fatal but warn so user knows which presets will work.
if command -v uvx >/dev/null 2>&1; then
  ok "uvx present — uv-based MCP servers (fetch, git, time, …) available"
else
  warn "uvx not found — uv-based MCP presets (fetch, git, time) won't run"
  warn "  install: comes with uv (already required); make sure uv is on PATH"
fi
if command -v npx >/dev/null 2>&1; then
  ok "npx present — npm-based MCP servers (memory, sequential-thinking, …) available"
else
  warn "npx not found — npm-based MCP presets (memory, sequential-thinking, filesystem) won't run"
  warn "  install: https://nodejs.org or  curl -fsSL https://fnm.vercel.app/install | bash && fnm install --lts"
fi

if ! command -v systemctl >/dev/null 2>&1; then
  err "systemctl not found. This installer needs systemd (most modern distros)."
  exit 1
fi
ok "systemctl present"

# ----- 2. Python deps ----------------------------------------------------
bold "2/5  Installing Python dependencies (uv sync)"
uv sync --quiet
ok "deps installed"

# ----- 3. .env -----------------------------------------------------------
bold "3/5  Configuring .env"
if [[ -f .env ]]; then
  ok ".env already exists — keeping it as is"
else
  # Token: prefer openssl, fall back to /dev/urandom
  if command -v openssl >/dev/null 2>&1; then
    TOKEN="$(openssl rand -hex 32)"
  else
    TOKEN="$(head -c 32 /dev/urandom | xxd -p -c 999)"
  fi

  echo
  echo "  Archive dir = where Muse can read/write (NEVER point at \$HOME or /)"
  ARCHIVE="$(ask 'Archive dir (absolute path):' "$HOME/muselab-archive")"
  ARCHIVE="${ARCHIVE/#\~/$HOME}"
  mkdir -p "$ARCHIVE"

  cat > .env <<EOF
# Generated by install-linux.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
MUSELAB_TOKEN=$TOKEN
MUSELAB_ROOT=$ARCHIVE
MUSELAB_HOST=127.0.0.1
MUSELAB_PORT=8765
MUSELAB_MODEL=claude-sonnet-4-6
EOF
  chmod 600 .env
  ok ".env created (mode 600)"
  ok "  MUSELAB_ROOT = $ARCHIVE"
  ok "  MUSELAB_TOKEN = ${TOKEN:0:6}…${TOKEN: -4}  (full token saved in .env)"

  # First-time setup: drop a CLAUDE.md template + subdirectory skeleton, and
  # walk the user through a short intake to populate the holistic profile.
  if [[ ! -f "$ARCHIVE/CLAUDE.md" ]]; then
    echo
    echo "  Muse is one assistant that helps you across health / career / "
    echo "  investment / family / life — simultaneously. To do that well, it"
    echo "  needs your basic profile and somewhere to find your real documents."
    echo "  This is a 2-minute intake; you can skip any question (press Enter)."
    REPLY="$(ask 'Set up archive skeleton + CLAUDE.md now? [Y/n]:' 'Y')"
    if [[ "$REPLY" =~ ^[Yy] ]]; then
      # 1) Copy subdirectory skeleton (health/ career/ investment/ family/
      #    notes/ archives/, each with a README explaining what to put there).
      for sub in health work money people notes archives; do
        if [[ ! -d "$ARCHIVE/$sub" ]]; then
          mkdir -p "$ARCHIVE/$sub"
          cp "scripts/templates/archive-skeleton/$sub/README.md" \
             "$ARCHIVE/$sub/README.md"
        fi
      done
      ok "archive skeleton created under $ARCHIVE/"

      # 2) Quick intake — just enough to make Muse's first reply useful.
      # All questions are open-ended so they fit students / employees / freelancers /
      # parents / retirees alike. Press Enter to skip any.
      echo
      echo "  --- Quick intake (press Enter to skip any) ---"
      INTAKE_NAME="$(ask 'How should Muse address you?' '')"
      INTAKE_BIRTH="$(ask 'Birth year (or just an age range):' '')"
      INTAKE_CITY="$(ask 'Where do you live?' '')"
      INTAKE_DOING="$(ask 'What occupies most of your week? (study / job / freelance / care / retirement / …)' '')"
      INTAKE_STAGE="$(ask 'One sentence about your life stage right now:' '')"
      INTAKE_GOAL="$(ask 'One main goal for this year:' '')"
      INTAKE_HEALTH="$(ask 'Top health concern right now (or "none"):' '')"

      # 3) Write CLAUDE.md with the intake values prefilled.
      sed -e "s|%DATE%|$(date +%Y-%m-%d)|" \
        scripts/templates/default-CLAUDE.md > "$ARCHIVE/CLAUDE.md"
      # Patch the empty profile slots with whatever the user gave. Each
      # substitution targets the END of the matching "- 标签：" line.
      _patch() {
        local label="$1" value="$2"
        [[ -z "$value" ]] && return
        # escape | for sed and append after the colon
        local esc
        esc="$(printf '%s' "$value" | sed -e 's/[\\&|]/\\&/g')"
        sed -i -E "0,/^(- $label：)$/{s||\1 $esc|}" "$ARCHIVE/CLAUDE.md"
      }
      _patch "称呼 / 名字（你希望 Muse 叫你什么）" "$INTAKE_NAME"
      _patch "出生年份（年龄段就行，不必精确）"     "$INTAKE_BIRTH"
      _patch "现在住在"                              "$INTAKE_CITY"
      _patch "我现在主要在做"                        "$INTAKE_DOING"
      _patch "这一年最想做成的一件事"               "$INTAKE_GOAL"
      _patch "当前最关心的健康问题（如有）"         "$INTAKE_HEALTH"
      # life stage 自由文本，放在「一句话现在」上方的备注里
      if [[ -n "$INTAKE_STAGE" ]]; then
        local esc
        esc="$(printf '%s' "$INTAKE_STAGE" | sed -e 's/[\\&|]/\\&/g')"
        sed -i "s|（如：「大三在准备保研」|$esc\\n\\n（如：「大三在准备保研」|" \
          "$ARCHIVE/CLAUDE.md"
      fi

      ok "CLAUDE.md → $ARCHIVE/CLAUDE.md (with your intake answers prefilled)"
      echo
      echo "  📋 Next steps (放什么完全看你自己阶段):"
      echo "    • Health: 体检 / 补剂 / 训练记录 → $ARCHIVE/health/"
      echo "    • Work:   学业材料 / 简历 / 作品集 / 项目 → $ARCHIVE/work/"
      echo "    • Money:  预算 / 持仓 / 学贷 / 保单 → $ARCHIVE/money/"
      echo "    • People: 关心的人的资料 → $ARCHIVE/people/"
      echo "    • Open $ARCHIVE/CLAUDE.md to fill in any blank fields you skipped"
      echo "  Each subdir has a README.md explaining what fits and what doesn't."
      echo "  Muse will see everything on your next chat — no restart needed."
    fi
  fi
fi

# ----- 4. systemd user service -------------------------------------------
bold "4/5  Installing systemd --user service"
UNIT_DIR="$HOME/.config/systemd/user"
mkdir -p "$UNIT_DIR"
sed -e "s|{{REPO_PATH}}|$REPO|g" \
    -e "s|{{UV_PATH}}|$UV|g" \
    scripts/templates/muselab.service.tmpl > "$UNIT_DIR/muselab.service"
ok "unit file: $UNIT_DIR/muselab.service"

systemctl --user daemon-reload
systemctl --user enable --now muselab.service
sleep 1
if systemctl --user is-active --quiet muselab.service; then
  ok "service is active"
else
  err "service failed to start — check logs: journalctl --user -u muselab -n 50"
  exit 1
fi

# ----- 5. Linger (so service runs even when you're not logged in) --------
bold "5/5  Enable user lingering (so service survives logout / reboot)"
if loginctl show-user "$USER" 2>/dev/null | grep -q "Linger=yes"; then
  ok "linger already enabled for $USER"
else
  warn "linger NOT enabled — service will stop when you log out / reboot without login"
  warn "  To enable (requires sudo):"
  warn "    sudo loginctl enable-linger $USER"
fi

echo
bold "✓ muselab installed"
echo  "  Open  → http://localhost:8765"
echo  "  Token → grep MUSELAB_TOKEN .env"
echo
echo  "  Useful commands:"
echo  "    systemctl --user status muselab     # check status"
echo  "    systemctl --user restart muselab    # restart"
echo  "    journalctl --user -u muselab -f     # tail logs"
echo  "    bash scripts/uninstall-linux.sh     # remove autostart"
