#!/usr/bin/env bash
# muselab — one-shot Linux installer (user-level systemd service)
# Usage: bash scripts/install-linux.sh
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"

bold() { printf "\033[1m%s\033[0m\n" "$*"; }
ok()   { printf "  \033[32m✓\033[0m %s\n" "$*"; }
warn() { printf "  \033[33m!\033[0m %s\n" "$*"; }
err()  { printf "  \033[31m✗\033[0m %s\n" "$*" >&2; }
ask()  { local q="$1" def="${2:-}" ans; read -rp "  $q ${def:+[$def]} " ans; echo "${ans:-$def}"; }

bold "muselab — Linux installer"
echo  "  Repo: $REPO"
echo

# ----- 1. Prerequisites ---------------------------------------------------
bold "1/5  Checking prerequisites"
if ! command -v uv >/dev/null 2>&1; then
  err "uv not found. Install it first:"
  echo "      curl -LsSf https://astral.sh/uv/install.sh | sh"
  exit 1
fi
UV="$(command -v uv)"
ok "uv: $UV"

if ! command -v claude >/dev/null 2>&1; then
  warn "claude CLI not found. Anthropic models won't work until you install it"
  warn "  and run 'claude login'. Non-Claude providers will still work via API keys."
else
  ok "claude CLI: $(command -v claude)"
fi

if ! command -v systemctl >/dev/null 2>&1; then
  err "systemctl not found. This installer needs systemd (most modern distros)."
  exit 1
fi
ok "systemctl present"

# ----- 2. Python deps ----------------------------------------------------
bold "2/5  Installing Python dependencies (uv sync)"
uv sync --quiet
ok "deps installed"

# ----- 3. .env -----------------------------------------------------------
bold "3/5  Configuring .env"
if [[ -f .env ]]; then
  ok ".env already exists — keeping it as is"
else
  # Token: prefer openssl, fall back to /dev/urandom
  if command -v openssl >/dev/null 2>&1; then
    TOKEN="$(openssl rand -hex 32)"
  else
    TOKEN="$(head -c 32 /dev/urandom | xxd -p -c 999)"
  fi

  echo
  echo "  Archive dir = where Muse can read/write (NEVER point at \$HOME or /)"
  ARCHIVE="$(ask 'Archive dir (absolute path):' "$HOME/muselab-archive")"
  ARCHIVE="${ARCHIVE/#\~/$HOME}"
  mkdir -p "$ARCHIVE"

  cat > .env <<EOF
# Generated by install-linux.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
MUSELAB_TOKEN=$TOKEN
MUSELAB_ROOT=$ARCHIVE
MUSELAB_HOST=127.0.0.1
MUSELAB_PORT=8765
MUSELAB_MODEL=claude-sonnet-4-6
EOF
  chmod 600 .env
  ok ".env created (mode 600)"
  ok "  MUSELAB_ROOT = $ARCHIVE"
  ok "  MUSELAB_TOKEN = ${TOKEN:0:6}…${TOKEN: -4}  (full token saved in .env)"
fi

# ----- 4. systemd user service -------------------------------------------
bold "4/5  Installing systemd --user service"
UNIT_DIR="$HOME/.config/systemd/user"
mkdir -p "$UNIT_DIR"
sed -e "s|{{REPO_PATH}}|$REPO|g" \
    -e "s|{{UV_PATH}}|$UV|g" \
    scripts/templates/muselab.service.tmpl > "$UNIT_DIR/muselab.service"
ok "unit file: $UNIT_DIR/muselab.service"

systemctl --user daemon-reload
systemctl --user enable --now muselab.service
sleep 1
if systemctl --user is-active --quiet muselab.service; then
  ok "service is active"
else
  err "service failed to start — check logs: journalctl --user -u muselab -n 50"
  exit 1
fi

# ----- 5. Linger (so service runs even when you're not logged in) --------
bold "5/5  Enable user lingering (so service survives logout / reboot)"
if loginctl show-user "$USER" 2>/dev/null | grep -q "Linger=yes"; then
  ok "linger already enabled for $USER"
else
  warn "linger NOT enabled — service will stop when you log out / reboot without login"
  warn "  To enable (requires sudo):"
  warn "    sudo loginctl enable-linger $USER"
fi

echo
bold "✓ muselab installed"
echo  "  Open  → http://localhost:8765"
echo  "  Token → grep MUSELAB_TOKEN .env"
echo
echo  "  Useful commands:"
echo  "    systemctl --user status muselab     # check status"
echo  "    systemctl --user restart muselab    # restart"
echo  "    journalctl --user -u muselab -f     # tail logs"
echo  "    bash scripts/uninstall-linux.sh     # remove autostart"
