# muselab — one-shot Windows installer (Task Scheduler, at logon)
# Run from the repo root in PowerShell:
#   powershell -ExecutionPolicy Bypass -File scripts\install-windows.ps1
# (Default ExecutionPolicy 'Restricted' blocks unsigned scripts; -Bypass is per-invocation.)

$ErrorActionPreference = "Stop"
$Repo = (Resolve-Path "$PSScriptRoot\..").Path
Set-Location $Repo

function Bold($s) { Write-Host $s -ForegroundColor White }
function Ok($s)   { Write-Host "  [+] $s" -ForegroundColor Green }
function Warn($s) { Write-Host "  [!] $s" -ForegroundColor Yellow }
function Err($s)  { Write-Host "  [x] $s" -ForegroundColor Red }
function Ask($q, $def="") {
  $prompt = if ($def) { "  $q [$def]" } else { "  $q" }
  $a = Read-Host $prompt
  if ([string]::IsNullOrWhiteSpace($a)) { return $def } else { return $a }
}

Bold "muselab — Windows installer"
Write-Host "  Repo: $Repo"
Write-Host

# ----- 1. Prerequisites ---------------------------------------------------
Bold "1/5  Checking prerequisites"
$uv = Get-Command uv -ErrorAction SilentlyContinue
if (-not $uv) {
  Err "uv not found. Install it first:"
  Write-Host "      powershell -c `"irm https://astral.sh/uv/install.ps1 | iex`""
  exit 1
}
$UvPath = $uv.Source
Ok "uv: $UvPath"

$claude = Get-Command claude -ErrorAction SilentlyContinue
if (-not $claude) {
  Warn "claude CLI not found. Anthropic models won't work until you install it"
  Warn "  and run 'claude login'. Non-Claude providers will still work via API keys."
} else {
  Ok "claude CLI: $($claude.Source)"
}

# ----- 2. Python deps -----------------------------------------------------
Bold "2/5  Installing Python dependencies (uv sync)"
& $UvPath sync --quiet
if ($LASTEXITCODE -ne 0) { Err "uv sync failed"; exit 1 }
Ok "deps installed"

# ----- 3. .env ------------------------------------------------------------
Bold "3/5  Configuring .env"
$EnvPath = Join-Path $Repo ".env"
if (Test-Path $EnvPath) {
  Ok ".env already exists — keeping it as is"
} else {
  # 64 hex chars (256-bit token) — uses crypto-grade RNG
  $bytes = New-Object 'System.Byte[]' 32
  [Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($bytes)
  $Token = ($bytes | ForEach-Object { "{0:x2}" -f $_ }) -join ""

  Write-Host
  Write-Host "  Archive dir = where Muse can read/write (NEVER point at your user dir or C:\)"
  $defArchive = Join-Path $env:USERPROFILE "muselab-archive"
  $Archive = Ask "Archive dir (absolute path):" $defArchive
  if (-not (Test-Path $Archive)) { New-Item -ItemType Directory -Path $Archive | Out-Null }

  $now = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
  @"
# Generated by install-windows.ps1 on $now
MUSELAB_TOKEN=$Token
MUSELAB_ROOT=$($Archive -replace '\\','/')
MUSELAB_HOST=127.0.0.1
MUSELAB_PORT=8765
MUSELAB_MODEL=claude-sonnet-4-6
"@ | Set-Content -Path $EnvPath -Encoding ascii

  # Restrict ACL to current user (rough equivalent of `chmod 600`)
  $acl = Get-Acl $EnvPath
  $acl.SetAccessRuleProtection($true, $false)
  $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "$env:USERNAME","FullControl","Allow")
  $acl.SetAccessRule($rule)
  Set-Acl -Path $EnvPath -AclObject $acl

  Ok ".env created (ACL restricted to $env:USERNAME)"
  Ok "  MUSELAB_ROOT = $Archive"
  Ok "  MUSELAB_TOKEN = $($Token.Substring(0,6))...$($Token.Substring($Token.Length - 4))  (full token in .env)"
}

# ----- 4. Scheduled Task --------------------------------------------------
Bold "4/5  Registering Scheduled Task (runs at logon)"
$TaskName  = "Muselab"
$LogDir    = Join-Path $env:LOCALAPPDATA "muselab\logs"
if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Path $LogDir -Force | Out-Null }

# Action: invoke uv with full args via cmd so we can redirect stdout/stderr
$cmdLine = "/c `"`"$UvPath`" run python -m backend.main >> `"$LogDir\stdout.log`" 2>> `"$LogDir\stderr.log`"`""
$Action  = New-ScheduledTaskAction -Execute "cmd.exe" -Argument $cmdLine -WorkingDirectory $Repo
$Trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$Settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -StartWhenAvailable `
  -RestartCount 5 -RestartInterval (New-TimeSpan -Minutes 1) `
  -ExecutionTimeLimit (New-TimeSpan -Days 365)
$Principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive

# Remove any prior version
if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}
Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger `
  -Settings $Settings -Principal $Principal | Out-Null
Ok "Scheduled Task '$TaskName' registered (trigger: at logon)"

# Start it now so the user doesn't have to log out/in
Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 2

# ----- 5. Sanity check ----------------------------------------------------
Bold "5/5  Sanity check"
try {
  $r = Invoke-WebRequest -Uri "http://127.0.0.1:8765/" -UseBasicParsing -TimeoutSec 5
  Ok "muselab responding at http://localhost:8765"
} catch {
  Warn "couldn't reach http://localhost:8765 yet — give it a few more seconds"
  Warn "  tail logs: Get-Content -Wait `"$LogDir\stderr.log`""
}

Write-Host
Bold "[OK] muselab installed"
Write-Host "  Open  -> http://localhost:8765"
Write-Host "  Token -> Select-String MUSELAB_TOKEN .env"
Write-Host
Write-Host "  Useful commands:"
Write-Host "    Get-ScheduledTask -TaskName Muselab    # check status"
Write-Host "    Stop-ScheduledTask  -TaskName Muselab  # stop"
Write-Host "    Start-ScheduledTask -TaskName Muselab  # start"
Write-Host "    Get-Content -Wait `"$LogDir\stderr.log`"   # tail logs"
Write-Host "    powershell -ExecutionPolicy Bypass -File scripts\uninstall-windows.ps1"
